package io.snw.entityapi.api;

public enum EntitySound {

    IDLE,
    HURT,
    DEATH,
    STEP,
    ATTACK,
    JUMP,
    BREATHE,
    LAY_EGG,
    STARE,
    TELEPORT,
    THROW,
    ANGRY,
    SHAKE,
    YES,
    NO;


    // TODO: Added some sounds :p (maybe we can use that)

   /** AmbientCave("ambient.cave.cave"),
    AmbientWeatherRain("ambient.weather.rain"),
    AmbientWeatherThunder("ambient.weather.thunder"),
    DamageFallBig("damage.fallbig"),
    DamageFallSmall("damage.fallsmall"),
    FireActive("fire.fire"),
    FireIgnite("fire.ignite"),
    LiquidLava("liquid.lava"),
    LiquidLavaPop("liquid.lavapop"),
    LiquidSplash("liquid.splash"),
    LiquidWater("liquid.water"),
    MobBlazeBreathe("mob.blaze.breathe"),
    MobBlazeDeath("mob.blaze.death"),
    MobBlazeHit("mob.blaze.hit"),
    MobCatHiss("mob.cat.hiss"),
    MobCatHitt("mob.cat.hitt"),
    MobCatMeow("mob.cat.meow"),
    MobCatPurr("mob.cat.purr"),
    MobCatPurreow("mob.cat.purreow"),
    MobChickenHurt("mob.chicken.hurt"),
    MobChickenPlop("mob.chicken.plop"),
    MobCowHurt("mob.cow.hurt"),
    MobCreeper("mob.creeper"),
    MobCreeperDeath("mob.creeperdeath"),
    MobEndermenDeath("mob.endermen.death"),
    MobEndermenHit("mob.endermen.hit"),
    MobEndermenIdle("mob.endermen.idle"),
    MobEndermenPortal("mob.endermen.portal"),
    MobEndermenScream("mob.endermen.scream"),
    MobEndermenStare("mob.endermen.stare"),
    MobGhastAffectionateScream("mob.ghast.affectionate scream"),
    MobGhastCharge("mob.ghast.charge"),
    MobGhastDeath("mob.ghast.death"),
    MobGhastFireball("mob.ghast.fireball"),
    MobGhastMoan("mob.ghast.moan"),
    MobGhastScream("mob.ghast.scream"),
    MobIrongolemDeath("mob.irongolem.death"),
    MobIrongolemHit("mob.irongolem.hit"),
    MobIrongolemThrow("mob.irongolem.throw"),
    MobIrongolemWalk("mob.irongolem.walk"),
    MobMagmacubeBig("mob.magmacube.big"),
    MobMagmacubeJump("mob.magmacube.jump"),
    MobMagmacubeSmall("mob.magmacube.small"),
    MobPigdeath("mob.pig.death"),
    MobSilverfishHit("mob.silverfish.hit"),
    MobSilverfishKill("mob.silverfish.kill"),
    MobSilverfishSay("mob.silverfish.say"),
    MobSilverfishStep("mob.silverfish.step"),
    MobSkeletonDeath("mob.skeleton.death"),
    MobSkeletonHurt("mob.skeleton.hurt"),
    MobSlimeattack("mob.slime.attack"),
    MobSpiderDeath("mob.spider.death"),
    MobWolfBark("mob.wolf.bark"),
    MobWolfDeath("mob.wolf.death"),
    MobWolfGrowl("mob.wolf.growl"),
    MobWolfHowl("mob.wolf.howl"),
    MobWolfHurt("mob.wolf.hurt"),
    MobWolfPanting("mob.wolf.panting"),
    MobWolfShake("mob.wolf.shake"),
    MobWolfWhine("mob.wolf.whine"),
    MobZombieMetal("mob.zombie.metal"),
    MobZombieWood("mob.zombie.wood"),
    MobZombieWoodbreak("mob.zombie.woodbreak"),
    MobZombie("mob.zombie"),
    MobZombiedeath("mob.zombie.death"),
    MobZombiehurt("mob.zombie.hurt"),
    MobZombiepigZpig("mob.zombiepig.zpig"),
    MobZombiepigZpigangry("mob.zombiepig.zpigangry"),
    MobZombiepigZpigdeath("mob.zombiepig.zpigdeath"),
    MobZombiepigZpighurt("mob.zombiepig.zpighurt"),
    NoteBass("note.bass"),
    NoteBassAttack("note.bassattack"),
    NoteBd("note.bd"),
    NoteHarp("note.harp"),
    NoteHat("note.hat"),
    NotePling("note.pling"),
    NoteSnare("note.snare"),
    PortalNear("portal.portal"),
    PortalTravel("portal.travel"),
    PortalTrigger("portal.trigger"),
    RandomBow("random.bow"),
    RandomBowhit("random.bowhit"),
    RandomBreak("random.break"),
    RandomBreath("random.breath"),
    RandomBurp("random.burp"),
    RandomChestclosed("random.chestclosed"),
    RandomChestopen("random.chestopen"),
    RandomClick("random.click"),
    RandomDoorClose("random.door_close"),
    RandomDoorOpen("random.door_open"),
    RandomDrink("random.drink"),
    RandomEat("random.eat"),
    RandomExplode("random.explode"),
    RandomFizz("random.fizz"),
    RandomFuse("random.fuse"),
    RandomGlass("random.glass"),
    RandomLevelup("random.levelup"),
    RandomOldExplode("random.old_explode"),
    RandomOrb("random.orb"),
    RandomPop("random.pop"),
    RandomSplash("random.splash"),
    RandomWoodClick("random.wood click"),
    StepCloth("step.cloth"),
    StepGrass("step.grass"),
    StepGravel("step.gravel"),
    StepSand("step.sand"),
    StepSnow("step.snow"),
    StepStone("step.stone"),
    StepWood("step.wood"),
    TilePistonIn("tile.piston.in"),
    TilePistonOut("tile.piston.out"),
    DamageHit("damage.hit"),
    DigCloth("dig.cloth"),
    DigGrass("dig.grass"),
    DigGravel("dig.gravel"),
    DigSand("dig.sand"),
    DigSnow("dig.snow"),
    DigStone("dig.stone"),
    DigWood("dig.wood"),
    LiquidSwim("liquid.swim"),
    MinecartBase("minecart.base"),
    MinecartInside("minecart.inside"),
    MobChickenSay("mob.chicken.say"),
    MobChickenStep("mob.chicken.step"),
    MobCowSay("mob.cow.say"),
    MobCowStep("mob.cow.step"),
    MobCreeperSay("mob.creeper.say"),
    MobPigDeath("mob.pig.death"),
    MobPigSay("mob.pig.say"),
    MobPigStep("mob.pig.step"),
    MobSheepSay("mob.sheep.say"),
    MobSheepShear("mob.sheep.shear"),
    MobSheepStep("mob.sheep.step"),
    MobSkeletonSay("mob.skeleton.say"),
    MobSkeletonStep("mob.skeleton.step"),
    MobSlimeAttack("mob.slime.attack"),
    MobSlimeBig("mob.slime.big"),
    MobSlimeSmall("mob.slime.small"),
    MobSpiderSay("mob.spider.say"),
    MobSpiderStep("mob.spider.step"),
    MobWolfStep("mob.wolf.step"),
    MobZombieDeath("mob.zombie.death"),
    MobZombieHurt("mob.zombie.hurt"),
    MobZombieSay("mob.zombie.say"),
    MobZombieStep("mob.zombie.step"),
    RandomClassicHurt("random.classic_hurt"),
    StepLadder("step.ladder"),
    MobBatDeath("mob.bat.death"),
    MobBatHurt("mob.bat.hurt"),
    MobBatIdle("mob.bat.idle"),
    MobBatTakeoff("mob.bat.takeoff"),
    MobEnderdragonEnd("mob.enderdragon.end"),
    MobEnderdragonGrowl("mob.enderdragon.growl"),
    MobEnderdragonHit("mob.enderdragon.hit"),
    MobEnderdragonWings("mob.enderdragon.wings"),
    MobWitherDeath("mob.wither.death"),
    MobWitherHurt("mob.wither.hurt"),
    MobWitherIdle("mob.wither.idle"),
    MobWitherShoot("mob.wither.shoot"),
    MobWitherSpawn("mob.wither.spawn"),
    MobZombieInfect("mob.zombie.infect"),
    MobZombieRemedy("mob.zombie.remedy"),
    MobZombieUnfect("mob.zombie.unfect"),
    RandomAnvilBreak("random.anvil_break"),
    RandomAnvilLand("random.anvil_land"),
    RandomAnvilUse("random.anvil_use");

    private final String sound;

    private EntitySound(String soundName) {
        this.sound = soundName;
    }

    public String getSound() {
        return this.sound;
    }  */
}